version: '3.9'
services:
  prom:
    image: prom/prometheus:latest
    container_name: dcutr-prom
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.2.0
    container_name: dcutr-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana:/grafana/dashboards:ro
    depends_on:
      - prom
    restart: unless-stopped
volumes: {}
