{{- if or .Values.secretConfig.operatorPrivateKey .Values.secretConfig.vaultToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agi-alpha-node.fullname" . }}
  labels:
    {{- include "agi-alpha-node.labels" . | nindent 4 }}
stringData:
  {{- if .Values.secretConfig.operatorPrivateKey }}
  operatorPrivateKey: {{ .Values.secretConfig.operatorPrivateKey | quote }}
  {{- end }}
  {{- if .Values.secretConfig.vaultToken }}
  vaultToken: {{ .Values.secretConfig.vaultToken | quote }}
  {{- end }}
{{- end }}
