{{- if .Values.secretConfig.operatorPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agi-alpha-node.fullname" . }}-secrets
  labels:
    {{- include "agi-alpha-node.labels" . | nindent 4 }}
type: Opaque
data:
  OPERATOR_PRIVATE_KEY: {{ .Values.secretConfig.operatorPrivateKey | b64enc | quote }}
{{- end }}
