apiVersion: v1
kind: Service
metadata:
  name: {{ include "agi-alpha-node.fullname" . }}
  labels:
    {{- include "agi-alpha-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "agi-alpha-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
